In [1]:
from tensorflow.keras.preprocessing import image  # Import the file

In [2]:
img = image.load_img('Capture.PNG',target_size=(224,224))  #import a sample file also converting the image to a size

In [3]:
img_array =image.img_to_array(img)   # convert the image to an numpy array ( ed array)
img_array

array([[[239., 239., 239.],
        [239., 239., 239.],
        [239., 239., 239.],
        ...,
        [239., 239., 239.],
        [239., 239., 239.],
        [239., 239., 239.]],

       [[239., 239., 239.],
        [239., 239., 239.],
        [239., 239., 239.],
        ...,
        [239., 239., 239.],
        [239., 239., 239.],
        [239., 239., 239.]],

       [[239., 239., 239.],
        [239., 239., 239.],
        [239., 239., 239.],
        ...,
        [239., 239., 239.],
        [239., 239., 239.],
        [239., 239., 239.]],

       ...,

       [[239., 239., 239.],
        [239., 239., 239.],
        [239., 239., 239.],
        ...,
        [239., 239., 239.],
        [239., 239., 239.],
        [239., 239., 239.]],

       [[239., 239., 239.],
        [239., 239., 239.],
        [239., 239., 239.],
        ...,
        [239., 239., 239.],
        [239., 239., 239.],
        [239., 239., 239.]],

       [[239., 239., 239.],
        [239., 239., 239.],
        [239., 2

In [4]:
img_array.shape

(224, 224, 3)

In [5]:
# so we add expand image array 
import numpy as np
expanded_img_array = np.expand_dims(img_array,axis=0)
print(expanded_img_array.shape)

(1, 224, 224, 3)


In [6]:
expanded_img_array  # now 3d image ( RGB) has bcome 4 d array with batch having only 1 image  

array([[[[239., 239., 239.],
         [239., 239., 239.],
         [239., 239., 239.],
         ...,
         [239., 239., 239.],
         [239., 239., 239.],
         [239., 239., 239.]],

        [[239., 239., 239.],
         [239., 239., 239.],
         [239., 239., 239.],
         ...,
         [239., 239., 239.],
         [239., 239., 239.],
         [239., 239., 239.]],

        [[239., 239., 239.],
         [239., 239., 239.],
         [239., 239., 239.],
         ...,
         [239., 239., 239.],
         [239., 239., 239.],
         [239., 239., 239.]],

        ...,

        [[239., 239., 239.],
         [239., 239., 239.],
         [239., 239., 239.],
         ...,
         [239., 239., 239.],
         [239., 239., 239.],
         [239., 239., 239.]],

        [[239., 239., 239.],
         [239., 239., 239.],
         [239., 239., 239.],
         ...,
         [239., 239., 239.],
         [239., 239., 239.],
         [239., 239., 239.]],

        [[239., 239., 239.],
       

In [7]:
import tensorflow
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D

In [8]:
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input

In [9]:
model = ResNet50(weights='imagenet',include_top=False,input_shape=(224,224,3))  # Model scale down image 224,224,3 
                                                                                # incluse False as we creating top layer
                                                                                # We are not training model we are using
model.trainable = False

model = tensorflow.keras.Sequential([
    model,
    GlobalMaxPooling2D()                                                        # this is our top layer
])

In [10]:
preprocessing_img = preprocess_input(expanded_img_array)  # Batch of image is preprocessed which comes in Reset ( Preprocessing )
print(expanded_img_array.shape)                           # Input needs to be converted RGB to BGR - Colorcentered and zero centered
preprocessing_img

(1, 224, 224, 3)


array([[[[135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ],
         ...,
         [135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ]],

        [[135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ],
         ...,
         [135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ]],

        [[135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ],
         ...,
         [135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ]],

        ...,

        [[135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ],
         ...,
         [135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ],
         [135.061, 122.221, 115.32 ]],

        [[

In [11]:
model.predict(preprocessing_img)  # we get a numpy array

1/1 [==============================] - 1s 1s/step


array([[6.774972 , 8.687267 , 2.3820698, ..., 1.2814876, 1.2573717,
        4.1461544]], dtype=float32)

In [12]:
model.predict(preprocessing_img).shape

1/1 [==============================] - 0s 93ms/step


(1, 2048)

In [16]:
model.predict(preprocessing_img).flatten().shape  # to ceovert to 1D array

1/1 [==============================] - 0s 99ms/step


(2048,)

In [ ]:
# we normalize the value i.e. between 0-1
from numpy.linalg import norm
norm(model.predict(preprocessing_img).flatten())
model.predict(model.predict(preprocessing_img).flatten())/norm(model.predict(model.predict(preprocessing_img).flatten()))

1/1 [==============================] - 0s 96ms/step


In [13]:
from numpy.linalg import norm
import numpy as np

In [ ]:
model.predict(model.predict(preprocessing_img).flatten())/norm(model.predict(model.predict(preprocessing_img).flatten()))

1/1 [==============================] - 0s 98ms/step


In [ ]:
np.sqrt(model.predict(model.predict(preprocessing_img).flatten())/norm(model.predict(model.predict(preprocessing_img).flatten())))